### ISSUE TITLE
🐛 Bug Report: Reddit error 500 "null": "Internal Server Error"

### ISSUE THREAD

**Issue by reterkha** [redlib-org/redlib#100]
## Describe the bug

Going to my own instance I get this error:

Reddit error 500 "null": "Internal Server Error"

Docker logs:
Starting Redlib...
Running Redlib v0.31.0 on 0.0.0.0:8080!
 ERROR redlib::utils > Error page rendered: Reddit error 500 "null": "Internal Server Error"
 ERROR redlib::utils > Error page rendered: Reddit error 500 "null": "Internal Server Error"
 ERROR redlib::utils > Error page rendered: Reddit error 500 "null": "Internal Server Error"
 ERROR redlib::utils > Error page rendered: Reddit error 500 "null": "Internal Server Error"
 ERROR redlib::utils > Error page rendered: Reddit error 500 "null": "Internal Server Error"

I'm the only one using this instance.
## What's the expected behavior?

View posts of subscribed subs.
## Additional context / screenshot

![image](https://github.com/redlib-org/redlib/assets/161308650/9851c2b8-8be7-40ae-868b-ab9bf7a27dd9)

**Comment by sigaloid** [comment]
Reddit is down :)

**Comment by Tokarak** [comment]
Confirmed here, too. Hopefully it's a reddit issue, and will go away by tomorrow. Reddit is not down (Reddit.com still loads).

**Comment by ButteredCats** [comment]
They've got something on their [status page](https://www.redditstatus.com/) about it so I'm sure it'll be solved soon.

**Comment by reterkha** [comment]
It's back on now.  Thankfully it wasn't a major issue.

**Comment by J4nniK** [comment]
In my case I can bypass this error if I go into the settings and then to Interface > Front page and then select All.
For some reason its crashing if I select Popular or Default but All works just fine
