### ISSUE TITLE
🐛 Bug Report: Reddit error 403 ""gated"": "Forbidden"

### ISSUE THREAD

**Issue by HexPum** [redlib-org/redlib#109]
Some subreddits seem to be blocked. When trying to view them this error message appears:

Reddit error 403 ""gated"": "Forbidden"

**Comment by Tokarak** [comment]
This is expected behavior! The API returns an error when trying to reach a banned community.

**Comment by sigaloid** [comment]
This applies to quarantined subs too, like r/edgy

**Comment by magicsk** [comment]
I found redlib instances where this works, is it posssible for selfhosted too or it's unknown what changes they made?
Example of such instance working on gated subreddit: https://redlib.tux.pizza/r/researchChemicals

**Comment by omnigenous** [comment]
> I found redlib instances where this works, is it posssible for selfhosted too or it's unknown what changes they made? Example of such instance working on gated subreddit: https://redlib.tux.pizza/r/researchChemicals

@magicsk I guess we can ask @tuxpizza!

**Comment by sigaloid** [comment]
:thinking: Sounds like a change we did between 0.31.0 and master changed the way we handled this? Bisect incoming

**Comment by sigaloid** [comment]
Very confused by this, looking at [this](https://github.com/redlib-org/redlib/compare/v0.30.1...v0.31.0?diff=unified&w=) it seems to be the entirety of oauth changes but I thought we fixed quarantined subs after that. :thinking:
