### ISSUE TITLE
New instances

### ISSUE THREAD

**Issue by ButteredCats** [redlib-org/redlib#11]
I'm aware it's a little early for this as there isn't a defined instance list yet but I've been planning to open my instance up once the rate limiting was fixed!

It's reachable at https://redlib.catsarch.com as well as http://redlib.catsarchywsyuss6jdxlypsw5dc7owd5u5tr6bujxb7o6xw2hipqehyd.onion/ over Tor.

They're both hosted in the US and neither are behind Cloudflare.

Thank you for keeping this amazing project alive!

**Comment by sigaloid** [comment]
Thank you very much for hosting an instance! I will take care of this when I get the instance list up and running! Big fan of your profile pic btw.

**Comment by sigaloid** [comment]
Done! https://github.com/redlib-org/redlib-instances

**Comment by ButteredCats** [comment]
I see the normal instance in there but what about the Tor one? Or am I just blind lol.

Also I love your profile pic too, cats for life 👍

**Comment by ButteredCats** [comment]
Now that I can actually search in there I see it's in instances.txt but it's missing in instances.md and instances.json. Taking a look at the old libreddit instances I see onion sites are in all three so I assume that's unintentional?

**Comment by sigaloid** [comment]
Just added it. When running the scanner, I forgot to enable the tor service. Fixed! (It hopefully won't disappear with the GH Actions rescan)

**Comment by ButteredCats** [comment]
Ah, alright. Thanks!
