### ISSUE TITLE
💡 Feature request: Custom port

### ISSUE THREAD

**Issue by Myzel394** [redlib-org/redlib#111]
## Is your feature request related to a problem? Please describe.

Please add an option to specify the internal port redlib listens to. 

## Describe the feature you would like to be implemented

Add a environment variable like `REDLIB_PORT` to be able to specify a value other than `8080`.

## Describe alternatives you've considered

You are currently able to define a different port on the outside (just like with every other docker container) like: `--port 1234:8080`. However, if you're for example using `network_mode: host` you're out of luck here :/

**Comment by ButteredCats** [comment]
You can already do something like `redlib -p 8081` to swap to port 8081.  Not too familiar with docker so I'm not sure if you can easily change the command it runs, but it's a workaround if you can.

**Comment by Myzel394** [comment]
So looks like this is already possible by using the env `PORT`, but it's not been documented yet. I opened a PR for it.
