### ISSUE TITLE
🐛 Bug Report: "submitted" view on user profile errors out

### ISSUE THREAD

**Issue by Kakifrucht** [redlib-org/redlib#116]
## Describe the bug

when visiting the my.instance.com/user/name/submitted, we get a parse error. otherwise user profiles are fine

error is: Failed to parse page JSON data: expected value at line 2 column 5

## Steps to reproduce the bug

1. open any user profile
2. click on the "submitted" tab

## What's the expected behavior?
the submitted user posts are shown

**Comment by sigaloid** [comment]
Fixed by https://github.com/redlib-org/redlib/commit/1715b36ae9f8d66758daaa7a5e7bc1a83f5e50e1

**Comment by Kakifrucht** [comment]
epic thanks
