### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 2 column 5

### ISSUE THREAD

**Issue by freedit-dev** [redlib-org/redlib#118]

**Comment by Owl-Tec** [comment]
Same issue here but my error message varies from "Failed to parse page JSON data: expected value at line 2 column 5" to "Failed to parse page JSON data: expected value at line 1 column 1":
<img width="1510" alt="Screenshot 2024-05-30 at 11 41 51 AM" src="https://github.com/redlib-org/redlib/assets/141874961/db7136ea-5710-45d4-876e-e944d2a871ae">


In my case I am running the following:
- redlib -> latest image
- My docker host (Synology DS1621+) has a AMD Ryzen V1500B CPU (so x86)


Here are on some logs from my container (after starting and restarting the container twice):
`
redlib
date,stream,content
2024/05/30 11:30:25,stderr, ERROR redlib::utils  > Error page rendered: Failed to parse page JSON data: expected value at line 2 column 5

2024/05/30 11:30:25,stderr, ERROR redlib::client > Got an invalid response from reddit expected value at line 2 column 5. Status code: 200 OK

2024/05/30 11:30:22,stderr, ERROR redlib::utils  > Error page rendered: Failed to parse page JSON data: expected value at line 2 column 5

2024/05/30 11:30:22,stderr, ERROR redlib::client > Got an invalid response from reddit expected value at line 2 column 5. Status code: 200 OK

2024/05/30 11:30:11,stderr, ERROR redlib::utils  > Error page rendered: Failed to parse page JSON data: expected value at line 2 column 5

2024/05/30 11:30:11,stderr, ERROR redlib::client > Got an invalid response from reddit expected value at line 2 column 5. Status code: 200 OK

2024/05/30 11:30:08,stderr, ERROR redlib::utils  > Error page rendered: Failed to parse page JSON data: expected value at line 2 column 5

2024/05/30 11:30:08,stderr, ERROR redlib::client > Got an invalid response from reddit expected value at line 2 column 5. Status code: 200 OK

2024/05/30 11:29:59,stdout,Running Redlib v0.31.0 on 0.0.0.0:8080!

2024/05/30 11:29:59,stdout,Starting Redlib...

2024/05/30 11:29:32,stderr, ERROR redlib::utils  > Error page rendered: Failed to parse page JSON data: expected value at line 2 column 5

2024/05/30 11:29:32,stderr, ERROR redlib::client > Got an invalid response from reddit expected value at line 2 column 5. Status code: 200 OK

2024/05/30 11:29:30,stderr, ERROR redlib::utils  > Error page rendered: Failed to parse page JSON data: expected value at line 2 column 5

2024/05/30 11:29:30,stderr, ERROR redlib::client > Got an invalid response from reddit expected value at line 2 column 5. Status code: 200 OK

2024/05/30 11:29:26,stderr, ERROR redlib::utils  > Error page rendered: Failed to parse page JSON data: expected value at line 2 column 5

2024/05/30 11:29:26,stderr, ERROR redlib::client > Got an invalid response from reddit expected value at line 2 column 5. Status code: 200 OK

2024/05/30 11:29:16,stdout,Running Redlib v0.31.0 on 0.0.0.0:8080!
`

**Comment by arch-btw** [comment]
Something I'm noticing is that the `.sh` version of reddit works, but the regular version is blocking me.

https://sh.reddit.com/r/all

vs

https://reddit.com/r/all

**Comment by Tokarak** [comment]
Seems like a Reddit server issue, then! Don't panic!

**Comment by GreatGreenStar** [comment]
Curiously https://old.reddit.com/ seems to work, I wonder if perhaps fall-back to such could be considered for the future?

**Comment by AlexPewMaster** [comment]
> [#71 (comment)](https://github.com/redlib-org/redlib/issues/71#issuecomment-2139970425)

My redlib instance is also stuck on version 0.31.0. I'm also having the same issue at my instance (https://redlib.reallyaweso.me).

**Comment by mirrorwitch** [comment]
My redlib is giving this issue also after upgrading to 0.34. amd64, and reddit for the same pages is working for me.

**Comment by Goosegit11** [comment]
@GreatGreenStar
> Curiously https://old.reddit.com/ seems to work also, I wonder if perhaps fall-back to sh.reddit.com and old.reddit.com could be considered for the future?

  I think it's a very good idea to add the ability to specify a backend of your choice!

**Comment by sigaloid** [comment]
The two problems here are separate, separate backends wouldn't have fixed this

They rolled out changes all at once, including the Android "fix", and broke the site for a bit. But they aren't related

**Comment by Goosegit11** [comment]
Separate backends are still a good feature that I would love to have

**Comment by sigaloid** [comment]
I'm not really sure what that would achieve. We can't use anything but oauth with the keys, the only other option is www and that's rate limited. They're not even really different back ends, they're all the same server

**Comment by binamov** [comment]
Forgive the ignorance, but when do you think the fix will roll out to quay? `latest` there seems to be 0.31

**Comment by oifj34f34f** [comment]
It seems that instances with older versions (https://libreddit.bus-hit.me/info) have started working again without the need for [this patch](https://github.com/redlib-org/redlib/commit/bd47c206a1d94c8382570b69730d72562d777454)
