### ISSUE TITLE
🐛 Bug Report: Bad news, `Couldn't send request to Reddit: error trying to connect: tcp connect error: Connection refused (os error 111)`

### ISSUE THREAD

**Issue by freedit-dev** [redlib-org/redlib#12]
I set up an instance on 2023-12-27(<https://redlib.freedit.eu/info>) and it worked well at that time. And today, i got `Couldn't send request to Reddit: error trying to connect: tcp connect error: Connection refused (os error 111)`

Even the latest commit doesn't work.

**Comment by sigaloid** [comment]
That is a version of Libreddit, not Redlib (rc2 was only ever Libreddit + the text in the top isn't replaced). Try the latest redlib docker tag. 

Though, that error is very weird, I don't know why that would ever happen. It looks like some kind of system issue that it can't even open up a socket to reddit. Is it IPV6 only?

**Comment by freedit-dev** [comment]
Sorry, I misconfiged it. redlib works well.

**Comment by sigaloid** [comment]
Hi @freedit-dev, just wanted to confirm a few things: May I add your instance to the instance list? And if so, what is the country of hosting, and does it use cloudflare? Thanks!

**Comment by freedit-dev** [comment]
@sigaloid Thanks for your great work. It's my honor to offer this instance.

https://redlib.freedit.eu	WWW 	v0.30.2 	🇺🇸 US

**Comment by freedit-dev** [comment]
@sigaloid Sorry for mention that https://redlib.freedit.eu/ is behind cloudflare
