### ISSUE TITLE
Docker image stuck at version 0.31 and won't build

### ISSUE THREAD

**Issue by Kirk1984** [redlib-org/redlib#122]
Thats pretty much it.

The curl link in the Dockerfile fails.

**Comment by C8opmBM** [comment]
Im pulling `latest` tag, but still on 0.31.
And 0.31 is broken. Please fix tyvm! ❤️

**Comment by Kirk1984** [comment]
Since i arrived at work and being paid for doing nothing :) i whipped up a quick Dockerfile to build a current image:

`
FROM rust:bookworm as builder
WORKDIR /home/rust/src
RUN git clone --depth=1 https://github.com/redlib-org/redlib.git .
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update
RUN apt-get install ca-certificates -y
COPY --from=builder /home/rust/src/target/release/redlib /usr/local/bin/redlib
RUN chmod a+x /usr/local/bin/redlib
RUN adduser --home /nonexistent --no-create-home --disabled-password redlib
USER redlib
EXPOSE 8080
CMD ["redlib"]
`

**Comment by xatier** [comment]
@necaran thanks for the `Dockerfile`, can confirm this works for me. Also, I used `alpine:3.20`, just FYI.

**Comment by rockerBOO** [comment]
This Dockerfile works with updating the link to the release. There may be some things changing with the release though. 

```dockerfile
FROM rust:alpine3.19

ARG TARGET

RUN apk add --no-cache curl

RUN (curl -Lo /usr/local/bin/redlib https://github.com/redlib-org/redlib/releases/download/$TARGET/redlib)
RUN chmod +x /usr/local/bin/redlib

RUN adduser --home /nonexistent --no-create-home --disabled-password redlib
USER redlib

# Tell Docker to expose port 8080
EXPOSE 8080

# Run a healthcheck every minute to make sure redlib is functional
HEALTHCHECK --interval=1m --timeout=3s CMD wget --spider --q http://localhost:8080/settings || exit 1

CMD ["redlib"]
```

**Comment by C8opmBM** [comment]
I do not know how to use this, same as probably many users. Can the `latest` tag be fixed preatty please?

**Comment by Kirk1984** [comment]
> I do not know how to use this, same as probably many users. Can the `latest` tag be fixed pretty please?

for a quick fix get a Dockerfile on your choosing from here, name it Dockerfile and put it int he same folder as the compose file. to build it you can use the compose.dev.yaml from the repo. you can see the build section in there when you compare it the the regular compose.yaml. then just 

docker compose build

and when its done

docker compose up -d

**Comment by C8opmBM** [comment]
> > I do not know how to use this, same as probably many users. Can the `latest` tag be fixed pretty please?
> 
> for a quick fix get a Dockerfile on your choosing from here, name it Dockerfile and put it int he same folder as the compose file. to build it you can use the compose.dev.yaml from the repo. you can see the build section in there when you compare it the the regular compose.yaml. then just
> 
> docker compose build
> 
> and when its done
> 
> docker compose up -d

Thanks, I managed to do it, but I have a very slow cpu `[+] Building 1502.9s (9/9) FINISHED` so it took a while. 
Now I don't know if I needed to create a volume to be persistent, I don't want to lose this and have to recompile, it kills my cpu and my nas is frozen during compiling.

Anyway, for the creator of the redlib, thank you for your efforts, but please, update the quay link to the latest. I do not understand where the problem is.
It would make my life so much easier. 
Thank you.

**Comment by Kirk1984** [comment]
> > > I do not know how to use this, same as probably many users. Can the `latest` tag be fixed pretty please?
> > 
> > 
> > for a quick fix get a Dockerfile on your choosing from here, name it Dockerfile and put it int he same folder as the compose file. to build it you can use the compose.dev.yaml from the repo. you can see the build section in there when you compare it the the regular compose.yaml. then just
> > docker compose build
> > and when its done
> > docker compose up -d
> 
> Thanks, I managed to do it, but I have a very slow cpu `[+] Building 1502.9s (9/9) FINISHED` so it took a while. Now I don't know if I needed to create a volume to be persistent, I don't want to lose this and have to recompile, it kills my cpu and my nas is frozen during compiling.
> 
> Anyway, for the creator of the redlib, thank you for your efforts, but please, update the quay link to the latest. I do not understand where the problem is. It would make my life so much easier. Thank you.

The image is not stored in a volume. If you would run for example “docker image prune” or “docker system prune” your build image would be deleted. I use my forgejo instance to store my build images. Maybe since you are on GitHub you could store it there (never done it myself):

https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

**Comment by rockerBOO** [comment]
> Thanks, I managed to do it, but I have a very slow cpu `[+] Building 1502.9s (9/9) FINISHED` so it took a while. Now I don't know if I needed to create a volume to be persistent, I don't want to lose this and have to recompile, it kills my cpu and my nas is frozen during compiling.

Using my [Dockerfile](https://github.com/redlib-org/redlib/issues/122#issuecomment-2143727362) won't require it to compile redlib but use the binary on the releases. Would be faster at least, takes about 2 seconds for me to build. But does download the release binary from GitHub.
