### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1

### ISSUE THREAD

**Issue by dave0003** [redlib-org/redlib#124]
## Describe the bug
When a link to an individual post, or post comments is clicked, this error is displayed consistently:

Failed to parse page JSON data: expected value at line 1 column 1

## Steps to reproduce the bug

Install 0.34.0, open redlib feed (displays fine), click on individual post or comments.

## What's the expected behavior?

Display the individual post.

## Additional context / screenshot

Running latest version 0.34.0 binary.

**Comment by reterkha** [comment]
I get the same error. 

When trying to go on the home page I get this:  `Couldn't send request to Reddit: error trying to connect: dns error: failed to lookup address information: Name does not resolve`

**Comment by gillescoolen** [comment]
Yep same here, maybe a change on reddit's side to combat external clients?

**Comment by dioxias** [comment]
wonder if it has any relation to the issue Android clients are facing? [revanced-patches#3253](https://github.com/ReVanced/revanced-patches/pull/3253)

**Comment by dave0003** [comment]
I'm still on 0.34.0, and it started working again, so I guess it's sporadic.  Hopefully there will be a new build to include the fix soon.

**Comment by binamov** [comment]
My 0.31 also started working.

**Comment by arloan** [comment]
> I get a similar but different error, the homepage or any sub page says: Failed to parse page JSON data: expected value at line 2 column 5.
> 
> I tried to run redlib v0.34.0 from the console, the the following lines were put:
> 
> ```
> Running Redlib v0.34.0 on 0.0.0.0:8080!
>  ERROR redlib::client > Got an invalid response from reddit expected value at line 2 column 5. Status code: 200 OK
>  ERROR redlib::utils  > Error page rendered: Failed to parse page JSON data: expected value at line 2 column 5
> ```

It works again since last night, dont know why.

**Comment by cmhobbs** [comment]
> I get the same error.
> 
> When trying to go on the home page I get this: `Couldn't send request to Reddit: error trying to connect: dns error: failed to lookup address information: Name does not resolve`

I'm getting this error with the homepage on the latest docker image (v 0.31.0).  Running the v0.34.0 binary directly resolves the issue.  I'm not sure what the delta between the two versions is, though.

**Comment by sigaloid** [comment]
The latest docker image should be 0.34.0

**Comment by cmhobbs** [comment]
> The latest docker image should be 0.34.0

It may be a different issue but pulling `quay.io/redlib/redlib:latest` results in v0.31.0 for me.

**Comment by sigaloid** [comment]
I think that's on your end - if I `pull quay.io/redlib/redlib:latest`, and run it, I see 0.34.0 in the bottom. Nonetheless, you're right- closing
