### ISSUE TITLE
🐛 Bug Report: Non-system themes not appearing when building from source

### ISSUE THREAD

**Issue by lilacpixel** [redlib-org/redlib#130]
## Describe the bug

When building the latest version from source to include the recent JSON bug fix, all themes disappear except for the default "System" theme.

## Steps to reproduce the bug

1. Create Dockerfile with the following contents:

```Dockerfile
FROM alpine:3.20.0 AS build

RUN apk add --no-cache cargo git

RUN git clone https://github.com/redlib-org/redlib
WORKDIR /redlib

RUN cargo build

FROM alpine:3.20.0

RUN apk add --no-cache libgcc

COPY --from=build /redlib/target/debug/redlib /usr/local/bin/

RUN adduser --home /nonexistent --no-create-home --disabled-password redlib
USER redlib

# Tell Docker to expose port 8080
EXPOSE 8080

# Run a healthcheck every minute to make sure redlib is functional
HEALTHCHECK --interval=1m --timeout=3s CMD wget --spider --q http://localhost:8080/settings || exit 1

CMD ["redlib"]
```

2. Build and run image.
3. Check settings page and verify that no non-default themes are available.

## What's the expected behavior?

All available Redlib themes should appear in the dropdown menu.

## Additional context / screenshot

![Screenshot 2024-06-01 at 11 15 28 AM](https://github.com/redlib-org/redlib/assets/44416326/54d4949f-8cc9-49f9-9428-dbec6cf7a7a2)

**Comment by Kakifrucht** [comment]
add the ``--release`` flag to the cargo build command

**Comment by lilacpixel** [comment]
> add the `--release` flag to the cargo build command

Beautiful, that was it--figured it had to be something silly I did 😉 Thanks so much!
