### ISSUE TITLE
💡 Feature request: Re-add android user agent...

### ISSUE THREAD

**Issue by sigaloid** [redlib-org/redlib#131]
#124 #118 #78 #117 #116 

All of these changes/issues were due to a bug in the API that has now been fixed. Do we re-add it to appear more legitimate as a mobile client?

**Comment by ButteredCats** [comment]
If it was truly a bug that caused it I'd say readd the user agent to look legit again.

Best case it continues to look legit and Reddit is none the wiser to who's a real Android client and who's a Redlib instance.

Worst case it happens again and we get some temporary breakage until the user agent is removed, and in that case probably don't readd it again. I also see the small possibility that Reddit begins to block requests that don't match the actual app and then it'd have to be readded anyways.

Real worst case if it gets left out is that Reddit looks further into Redlib, deems it a problem, and goes the Nitter route of attempting to smite it. That seems incredibly unlikely from just leaving out the user agent though.

**Comment by Kakifrucht** [comment]
the issue in #117 has started to reappear for me both on v0.31.0 and v0.34.0, only on the homepage when two or more subs have been subscribed to. viewing subs directly, r/popular and r/all and userprofiles still work.

**Comment by wuchyi** [comment]
Can confirm, the issue has popped up again on my instance running on v0.34.0 (quay.io official image, git commit `a6f901c09435da4157b17d57bdee98b4f65cc581`). 

Error message on frontpage:
`Couldn't send request to Reddit: error trying to connect: dns error: failed to lookup address information: Name does not resolve`

Weirdly enough this issue doesn't seem to hit all redlib instances all at once?

**Comment by ButteredCats** [comment]
Can confirm this is occasionally happening on my instance as well as a 429 from Reddit instantly followed by "Failed to parse page JSON data: EOF while parsing a value at line 1 column 0" on every page.

**Comment by sigaloid** [comment]
Really? We don't even include Android any more. Might be some weird rate limiting they're applying. If we can get a concise reproduction case I'd love to look into this further. 

I just pushed https://github.com/redlib-org/redlib/commit/997cd8f829f8be18d4fe051b19d318cf53df7cb3, now you can see the full path associated with any requests and the button will pre-fill the issue draft with the path. This will help a bunch with trying to identify the path problem that this issue is related to

![image](https://github.com/redlib-org/redlib/assets/69441971/bca93dd3-4810-4def-8520-1e9ff0e73bd8)
