### ISSUE TITLE
💡 Feature request: Improve search bar design on mobile devices

### ISSUE THREAD

**Issue by syeopite** [redlib-org/redlib#143]
## Is your feature request related to a problem? Please describe.

On devices with small screens the search bar becomes tiny and difficult to use, especially with longer text.  See screenshots below

## Describe the feature you would like to be implemented

For the search bar to become responsive and easier to use on mobile devices. For example by moving to its own row. See example mock-up below.

## Additional context / screenshot

How it currently is
<img width=300 src="https://github.com/redlib-org/redlib/assets/70992037/2cf9f6c5-0646-4173-b0a1-adf2b1a5b816"/>

Example mock-up of how it can be fixed:
<img width=300 src="https://github.com/redlib-org/redlib/assets/70992037/5bb912f8-1fdb-4323-b113-9e714a8875a9"/>

**Comment by oifj34f34f** [comment]
Here's how the search page looks on my small screen smartphone, the search input field does not have enough space for entering text (click to expand):

<img src="https://github.com/redlib-org/redlib/assets/128177553/f9b7dfb3-2c5d-4a60-9173-fa9ae0a7ed05" width="400" height="790">
