### ISSUE TITLE
🐛 Bug Report: REDLIB_DEFAULT_SUBSCRIPTIONS not working for multiple subscriptions

### ISSUE THREAD

**Issue by mokahless** [redlib-org/redlib#147]
## Describe the bug

When multiple subscriptions are added via REDLIB_DEFAULT_SUBSCRIPTIONS, redlib instance homepage spits out the error "Couldn't send request to Reddit: error trying to connect: dns error: failed to lookup address information: Name does not resolve"

Everything works fine if there is either 0 or 1 subscription.

Edit: Update: Also affects UI subscribe button. Accessed a fresh default instance in firefox incognito and homepage worked perfectly until I subscribed to a second subreddit.

## Steps to reproduce the bug

1. Create 0.34 docker instance via docker compose and the default compose.yml file
2. add REDLIB_DEFAULT_SUBSCRIPTIONS=funny+technology to the .env file
3. navigate to redlib instance home

or

2. Subscribe to any 2 subreddits via UI
3. navigate to redlib instance home

## What's the expected behavior?

Multi-subscription should appear at redlib instance homepage

## Additional context / screenshot

I found #117 which seems to be the exact error message, but a seemingly unrelated cause. As per this issue, I do get the same pihole entries. And nothing blocked.

Edit, it's basically the same error but here are the docker logs

```
Starting Redlib...
Running Redlib v0.34.0 on 0.0.0.0:8080!
 ERROR redlib::utils > Error page rendered: Couldn't send request to Reddit: error trying to connect: dns error: failed to lookup address information: Name does not resolve
```

Edit: made some edits when I realized this wasn't exclusive to .env subscriptions.

**Comment by Kakifrucht** [comment]
related to #117 and #131 

not related to this specific setting

**Comment by sigaloid** [comment]
I think this is fixed, https://github.com/redlib-org/redlib/pull/154

Reopen if not!
