### ISSUE TITLE
🐛 Bug Report: Couldn't send request to Reddit: error trying to connect: Unsuccessful reply: GeneralFailure

### ISSUE THREAD

**Issue by millionsofplayers** [redlib-org/redlib#153]
## Describe the bug
Today i found out that I can't use the redredlib.freedit.eu instance because on the homepage it returns the GeneralFailure error seen in the title

## Steps to reproduce the bug

1. Go to https://redlib.freedit.eu/r/Android
2. see error

## What's the expected behavior?
To be able to see a homepage of the subreddits i've subscribed to

**Comment by sigaloid** [comment]
Probably https://github.com/redlib-org/redlib/issues/155, let me know if the linked PR doesn't fix it (cc @freedit-dev)
