### ISSUE TITLE
🐛 Bug Report: Reddit rate limit exceeded

### ISSUE THREAD

**Issue by sigaloid** [redlib-org/redlib#155]
Background: #151

Looks like Reddit has started enforcing a rate limit even on the oauth routes. I'll explore a few options to bypass this.

**Comment by sigaloid** [comment]
Fixed :partying_face:

**Comment by paschun** [comment]
wow, that was quick, good job! thank you!

**Comment by Rosaboy** [comment]
Today Reddit deleted my posts, pfp and access to commenting cuz "We had a server error" and that rate limit to wait 800 seconds
