### ISSUE TITLE
🐛 Bug Report: Redlib constantly stops responding

### ISSUE THREAD

**Issue by ButteredCats** [redlib-org/redlib#157]
## Describe the bug
Running d045a5760ad9afbeb4ea76faf9c22e173d90bc7c Redlib constantly just outright stops responding until a restart.
This usually happens right after a `Error page rendered: Couldn't send request to Reddit: error trying to connect: dns error: failed to lookup address information: Name or service not known` in the logs. 

## Steps to reproduce the bug
Start Redlib, use it for a couple of minutes, and then watch the page never load.

## What's the expected behavior?
Redlib runs without any hitches.

## Additional context / screenshot
This is happening to both of my Redlib containers on my server, not on my desktop though. Probably related to having load on it again.

I'm also not seeing any of the warnings about refreshing the oauth token that just got added.

It's happening with about the same frequency as the ratelimiting was before, so maybe the refreshing is just broken?

**Comment by sigaloid** [comment]
Hm, sounds like it could be the same as [this](https://github.com/redlib-org/redlib/issues/150#issuecomment-2192915468) - can you turn on debug logs (set env var `RUST_LOG=redlib=trace`)

**Comment by sigaloid** [comment]
Okay, I don't think the problem is the locks. I'll stop trying to band-aid it and do a real solution, either tomorrow morning or on Friday.
