### ISSUE TITLE
🐛 Bug Report: Subscribe to Multireddit option missing

### ISSUE THREAD

**Issue by Tech-How** [redlib-org/redlib#159]
## Describe the bug
  When pasting a link to a multireddit from Reddit to import your subscriptions, there used to be an option labeled "Subscribe to Multireddit". Now, there is none.

## Steps to reproduce the bug

1. Go to https://redlib.freedit.eu/r/YouTube+pcmasterrace+iOS
2. Observe that there is no "Subscribe to multireddit" option at the top of the screen

## What's the expected behavior?
  There's an option to subscribe to the multireddit, so I can import my subscriptions.

**Comment by sigaloid** [comment]
Fixed :)
