### ISSUE TITLE
🐛 Bug Report: Disabling "Keep navbar fixed" makes the footer float on page

### ISSUE THREAD

**Issue by ButteredCats** [redlib-org/redlib#16]
## Describe the bug
When disabling the "Keep navbar fixed" option the footer starts at the bottom of the initial viewport and then stays floating in that spot after you scroll. It's not longer at the very bottom of the page.

## Steps to reproduce the bug
1. Go to settings
2. Uncheck "Keep navbar fixed"
3. Save
4. Scroll down, you'll see the footer is floating on the page

## What's the expected behavior?
The footer stays at the bottom of the page

## Additional context / screenshot
![Screenshot_20240103_190442](https://github.com/redlib-org/redlib/assets/37316782/1a201725-dc7d-4155-a15b-fb9086186b47)

After messing around with the CSS I found changing `position: absolute` to `position: relative` in the `body > footer` rules fixes this when "Keep navbar fixed" is disabled, but it breaks the footer when "Keep navbar fixed" is enabled.

**Comment by sigaloid** [comment]
This is related to this: https://github.com/libreddit/libreddit/pull/536/files

And that we added a footer (near https://github.com/libreddit/libreddit/commit/af6722c053e81a42f655a2aa768995a91893effd)

Unfortunately my CSS skills are subpar, so I can't find a fix immediately.

**Comment by ButteredCats** [comment]
Had a realization when I got the email from your reply and just gave it a quick test.

Removing `padding-bottom: var(--footer-height);` from `body.fixed_navbar` and removing `position: absolute;` from `body > footer` fixes this no matter what "Keep navbar fixed" is set to.

**Comment by sigaloid** [comment]
Sounds awesome! Want to submit a PR to get the credit?

**Comment by ButteredCats** [comment]
Done! #17
