### ISSUE TITLE
🐛 Bug Report: Pinned posts no longer at top of community/subreddit page

### ISSUE THREAD

**Issue by pbui** [redlib-org/redlib#167]
## Describe the bug

Pinned posts in subreddits no longer appear at the top of community page.

## Steps to reproduce the bug

Go to a subreddit that has pinned posts.  Notice that they are no longer at the top of the community page.

## What's the expected behavior?

Before 0.35.0, the pinned posts were at the top of the community page (ie. the first post)

## Additional context / screenshot

Example from r/2007scape showing pinned post in the middle of the community page (and not at the top).

![Screenshot from 2024-06-29 12-34-50](https://github.com/redlib-org/redlib/assets/3976244/ec610f96-089e-4c9e-90ea-5189ab056b10)

**Comment by sigaloid** [comment]
Thanks for the bug report! Fixed
