### ISSUE TITLE
Ordering incorrect

### ISSUE THREAD

**Issue by sigaloid** [redlib-org/redlib#170]
i believe something went wrong here. on v0.35.1 every ordering is now sorted by creation date, including Hot and Top.

_Originally posted by @Kakifrucht in https://github.com/redlib-org/redlib/issues/166#issuecomment-2201824145_

**Comment by sigaloid** [comment]
@Kakifrucht let me know if this doesn't fix it!

**Comment by Kakifrucht** [comment]
you only asked for feedback if it doesn't, but i can let you know that it does indeed fix it 😄

**Comment by sigaloid** [comment]
ty :smile_cat:
