### ISSUE TITLE
💡 Feature request: Logo change

### ISSUE THREAD

**Issue by SecularSteve** [redlib-org/redlib#203]
![logo](https://github.com/user-attachments/assets/f504ccf5-95dd-44e2-bc02-059229e40a57)

If it's going to be called "RedLib", might as well have something both "colour-appropriate", and differentiating enough to individualise it away from the original fork.

But that's just a suggestion. Maybe some have better ideas than me.

**Comment by SecularSteve** [comment]
> I've been wanting to switch the two letters in it to properly reflect the new name being RL instead of LR. But haven't had the chance to get a vector editor out in a while. A new color would be nice as well!

Something like this?

![logo](https://github.com/user-attachments/assets/039c99d4-d401-4f51-8c96-c681b4317c73)
![logo2](https://github.com/user-attachments/assets/c09319c7-58b7-4020-bd48-85aa6a1ccc1f)
![logo3](https://github.com/user-attachments/assets/57afbdb7-6f21-404c-8be1-8685226e77bb)

**Comment by sigaloid** [comment]
Looks great, if you submit a PR I'd be happy to merge it!
