### ISSUE TITLE
🐛 Bug Report: www.redditstatic.com link not converted to Redlib link

### ISSUE THREAD

**Issue by ButteredCats** [redlib-org/redlib#206]
## Describe the bug
In this post https://redlib.catsarch.com/r/mildlyinfuriating/comments/1exxowd/thanks_for_being_accessible/lja4766/?context=3 the second emote is not converted to a link

## Steps to reproduce the bug
1. Visit https://redlib.catsarch.com/r/mildlyinfuriating/comments/1exxowd/thanks_for_being_accessible/lja4766/?context=3
2. See second image in comment is broken
3. Right click on it > inspect, see img src is a www.redditstatic.com link.

## What's the expected behavior?
`https://www.redditstatic.com/` gets converted into `/static/`

## Additional context / screenshot
![Screenshot_20240821_190342](https://github.com/user-attachments/assets/489cbb12-e7a6-421f-9316-21d85426fe3c)
![Screenshot_20240821_190414](https://github.com/user-attachments/assets/de5155f2-5215-4cc2-afe6-c4ece189217c)

**Comment by sigaloid** [comment]
This points to a deeper issue with the format_url function and I'm not totally sure how trivial this would be to fix, but it causes privacy leaks by allowing through, so it would be ideal to fix this soon

**Comment by ButteredCats** [comment]
I already fixed it as part of https://github.com/redlib-org/redlib/pull/209 by wrapping that bit in a loop like I had done for the preview embeds.

Redlib's content security policy prevents any requests to Reddit though, so no privacy leaks here. Just some broken functionality.

**Comment by sigaloid** [comment]
:fearful: embarrassing lol that one slipped past me. Going to check it out today
