### ISSUE TITLE
[Question] What does HIDE_SIDEBAR_AND_SUMMARY do?

### ISSUE THREAD

**Issue by omnigenous** [redlib-org/redlib#210]
Couldn't find explanation in docs. Toggling this option doesn't seem to change anything

**Comment by syntheticbit** [comment]
It disables the sidebar shown on the right when viewing a subreddit.
Here's a screenshot of the r/selfhosted sidebar.
![image](https://github.com/user-attachments/assets/15a94ec6-e301-4e06-b549-9ebb98fbd7b5)
