### ISSUE TITLE
[Question] What does DEFAULT_FILTERS do?

### ISSUE THREAD

**Issue by omnigenous** [redlib-org/redlib#211]
Could found info on this env variable in documentation but there is field in `/info` path called `Filters` so I set `DEFAULT_FILTERS=string` but that string wasn't filtering posting in or out. What does this do? And why can't this setting be manipulated via UI?

**Comment by syntheticbit** [comment]
It's to block subreddits. It was requested here: https://github.com/redlib-org/redlib/issues/137
