### ISSUE TITLE
🐛 Bug Report: "Unauthorized"; fixed by restarting instance.

### ISSUE THREAD

**Issue by Tokarak** [redlib-org/redlib#22]
## Describe the bug

At some point, the instance seems to start receiving only "unauthorized" responses from Reddit (several hours). Restarting Redlib fixes the behaviour temporarily.

## Steps to reproduce the bug

That's all I know so far.

## Additional context / screenshot

I'm running Redlib on my laptop, and accessing the instance on localhost. It's a portable laptop, so I switch IPs often. The old Libreddit worked perfectly (even after the api changes), since I never hit rate limits.

Does Redlib have a logging feature, to help with debugging?

**Comment by sigaloid** [comment]
Is this after long periods of time? If so, it could be related to the OAuth token refreshing

Run with RUST_LOG=info to run with additional logging (works with release). 

```

**Comment by Tokarak** [comment]
That seems like a reasonable hypothesis. Could something be preventing the token refresh if the laptop is closed (sleeping) when the token expires?

**Comment by sigaloid** [comment]
Yes, that will inhibit the token daemon from refreshing - time spent suspended doesn't count towards the timer, so if you suspend for 12 hours, then wake it up, it will think there's still 24 hours left. https://github.com/tokio-rs/tokio/issues/5894#issuecomment-1656278884

Maybe it would make sense to catch an auth error in client.rs and then refresh the oauth client, in case there was any other problems. But for now, you can also cycle through auth tokens by simply restarting the program.

**Comment by Tokarak** [comment]
https://github.com/redlib-org/redlib/blob/0f148c58d3bb78b01d44edc7df5e7180c6363a12/src/oauth.rs#L111C1-L131C2

Seems like this loop could easily break for a number of reasons when the laptop is closed. Either a) a refresh is skipped because a laptop is closed or b) the wait timer pauses when the laptop is closed, meaning the OAuth token isn't refreshed when it's needed.

**Comment by Tokarak** [comment]
What I'll do is work out the exact error code and message Reddit sends when the OAuth token expires (this will take slightly more than 24 hours :)) (Or maybe the Reddit official or unofficial api docs can help); in the error handling atomically refresh the token, then retry the request. That way some conditions are met:
- The end user does not notice the error (apart from a few milliseconds longer delay on first connect).
- The token isn't refreshed on other reasons for "unauthorised" (potentially: private subreddits; deleted posts)
- A "dead" instance (0 users) doesn't send any extra requests to Reddit.

**Comment by ButteredCats** [comment]
Just ran into this issue too, except my instance is running on a server that's on 24/7.

It's been running without issue for over a week until today.

**Comment by sigaloid** [comment]
Hm, okay so we need to catch this in `client.rs`. Do you remember the exact error you got?

**Comment by ButteredCats** [comment]
Checking in the logs for that day the only things out of the ordinary I see are
`ERROR redlib::utils > Error page rendered: Unauthorized` and 
`ERROR redlib::utils > Error page rendered: Reddit is having issues, check if there's an outage`

Since then I've been running with RUST_LOG=info enabled in case it happens again but so far all has been good.

**Comment by sigaloid** [comment]
Ok, perfect - I'm glad I just added that error page logging in 3609564db0a1790571054541dbcecc7162b0787c :sweat_smile:  Will work on a possible fix for this

**Comment by sigaloid** [comment]
6c2579cda9efaeea0bfd8e4a53b298b2b1ef9c6e to possibly fix this. If anyone is experiencing this consistently, please test the latest docker container (just pushed).

**Comment by Tokarak** [comment]
The fix does not work.
`error!("Got a bad response from reddit {e}. Status code: {status}");` 
The above line never runs; it's necessary for the token refresh to happen.
It appears that the logic is just bad; I'll look over it soon. (It runs on a _parsing_ error)
