### ISSUE TITLE
🐛 Bug Report: Container Build failure.

### ISSUE THREAD

**Issue by kashmir772** [redlib-org/redlib#226]
## Describe the bug
The GitHub Container Build workflow is failing.  [See here](https://github.com/redlib-org/redlib/actions/runs/10692211829)

## Steps to reproduce the bug
Here is the error message that is being thrown

```
merge
Unable to download artifact(s): Artifact not found for name: digests
        Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
```

It looks like a bot committed this [change](https://github.com/redlib-org/redlib/commit/d0e081e6a0f9eb35aa481cb931a4e6ea3389fc58) which changed the version number of `download-artifact` but not the `upload-artifact`

## What's the expected behavior?

I think fix is that this line needs the version changed to `@v4.1.7`

https://github.com/redlib-org/redlib/blob/408ebe6ef1fc1be9933424c3b3f49cfb1fdbb125/.github/workflows/main-docker.yml#L66

But I don't know enough about Workflows to know if that is correct or not.

**Comment by sigaloid** [comment]
Closed, thanks! #234
