### ISSUE TITLE
🐛 Bug Report: Searching in multireddit error: Could'nt send request to Reddit: Reddit response was invalid

### ISSUE THREAD

**Issue by azizLIGHT** [redlib-org/redlib#228]
## Describe the bug
  Trying to search stuff restricted to a multireddit gives an error
`Couldn't send request to Reddit: Reddit response was invalid | /r/pics+pic/search.json?q=test&restrict_sr=on&include_over_18=on&raw_json=1`

## Steps to reproduce the bug
1. Go to `redlib_instance/r/pics+pic`
2. Type `test` in the search box at the top
3. Make sure checkbox in the searchbox is checked for `in /r/pics+pic`
4. Click arrow button or press enter
5. See error

## What's the expected behavior?
Expect to see list of posts that come from both and only /r/pics and /r/pic that match `test`
Multireddit here means a combo of subreddits like /r/pics+pic or /r/news+worldnews or any two or more subreddits combined with a + character

## Additional context / screenshot
- The correct results from both subreddits are available on old reddit page [here](https://old.reddit.com/r/pics+pic/search?q=test&restrict_sr=on)
- The results are also on old reddit json page [here](https://old.reddit.com/r/pics+pic/search.json?q=test&restrict_sr=on&include_over_18=on&raw_json=1)
- The results are also on normal reddit json page [here](https://www.reddit.com/r/pics+pic/search.json?q=test&restrict_sr=on&include_over_18=on&raw_json=1)

**Comment by ozen-m** [comment]
The same happens now on just normal subreddits. Even by not searching. Reddit api must have changed

Failed to parse page JSON data: expected value at line 1 column 1 | /r/popular/hot.json?&raw_json=1&geo_filter=GLOBAL

**Comment by azizLIGHT** [comment]
I think this error 

`Failed to parse page JSON data: expected value at line 1 column 1 | /r/popular/hot.json?&raw_json=1&geo_filter=GLOBAL`

is new and a separate issue. My error about the multireddit searches was happening since at least August 18, 2024

**Comment by sigaloid** [comment]
This looks like a plus-encoding issue - relevant code can be found by searching "%2B"
