### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1 | /r/popular/hot.json?

### ISSUE THREAD

**Issue by Shagon94** [redlib-org/redlib#231]
## Describe the bug

I tried to open the front page, I think reddit might be changing something. This worked fine up until today.

## Steps to reproduce the bug

1. Go to redlib.mydomain.com
2. observe error

## What's the expected behavior?

The page loads

## Additional context / screenshot

![image](https://github.com/user-attachments/assets/bb97809d-2fc5-41f3-8e1d-d79425be8b7e)

**Comment by Taubin** [comment]
Duplicate of #229
