### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by oifj34f34f** [redlib-org/redlib#24]
## Describe the bug

It seems the binary from "Releases" doesn't work on my system:

```
$ ./redlib
Starting Redlib...
Floating point exception (core dumped)
```

## OS

Arch Linux x86_64

**Comment by sigaloid** [comment]
Should be fixed now. I had to manually compile that release as the GH Action failed to trigger for some reason. Thanks for reporting!

**Comment by oifj34f34f** [comment]
@sigaloid, thank you!
