### ISSUE TITLE
🐛 Bug Report: OAuth token has expired. Please refresh the page!

### ISSUE THREAD

**Issue by DovletR** [redlib-org/redlib#245]
## Steps to reproduce the bug
Go to [(https://redlib.catsarch.com)](https://redlib.catsarch.com/) and it will say:

`OAuth token has expired. Please refresh the page!`

## What's the expected behavior?
To display any Reddit page.

**Comment by sigaloid** [comment]
This should appear for a few seconds to a minute at most and thus can't really be 'fixed' in the normal sense.
