### ISSUE TITLE
🐛 Bug Report: official instance currently responding with 502 error?

### ISSUE THREAD

**Issue by t-var-s** [redlib-org/redlib#27]
Please disregard this if any issues with https://redlib.matthew.science are not supposed to be reported here. 

`curl -v https://redlib.matthew.science/` has been responding with a 502 for about four hours.

**Comment by sigaloid** [comment]
Sorry about that, system update that didn't restart the container.

I'm rethinking using mine as the official instance as I don't know how well I can maintain its uptime, especially if bandwidth grows rapidly. But closing for now, as it's fixed
