### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1 | /r/popular/hot.json?

### ISSUE THREAD

**Issue by Inplex-sys** [redlib-org/redlib#270]
## Describe the bug
Failed to parse page JSON data: expected value at line 1 column 1 | /r/popular/hot.json?

## Steps to reproduce the bug

Going to any page on reddit

## What's the expected behavior?
Showing the page

**Comment by sigaloid** [comment]
What's the instance URL, git commit, and version? (info at `/info`)

**Comment by maxysoft** [comment]
Has been having the same issue for the past month. Sometimes works, but only if I open a page after a long "standby" and it works only one time. After that it stops working again.

https://redlib.maxynetwork.it/info

```
ERROR redlib::client > Got an invalid response from reddit expected value at line 1 column 1. Status code: 403 Forbidden
 ERROR redlib::utils  > Error page rendered: Failed to parse page JSON data: expected value at line 1 column 1
```

I'll try to use the https://github.com/iv-org/smart-ipv6-rotator and see if helps

**Comment by sigaloid** [comment]
That's a very outdated commit, please pull a new image

**Comment by sigaloid** [comment]
In general, if you get this error, ensure you're on the latest commit by pulling the latest image first. This exact error was fixed 2 weeks ago. Feel free to reopen or open a new issue if you can confirm the git commit is fresh.

**Comment by Setup2134** [comment]
> In general, if you get this error, ensure you're on the latest commit by pulling the latest image first. This exact error was fixed 2 weeks ago. Feel free to reopen or open a new issue if you can confirm the git commit is fresh.

I'm still getting this error on the latest docker image for redlib. Do you have an estimate for when the next redlib version will be released? (Which hopefully should fix the issue). Thanks.

**Comment by sigaloid** [comment]
The latest docker image doesn't run into the same error unless your IP is banned. A new release won't fix it for you, tagged images are based on `main` builds
