### ISSUE TITLE
🐛 Bug Report: panics that hang server

### ISSUE THREAD

**Issue by FireMasterK** [redlib-org/redlib#28]
## Describe the bug

I think when all worker threads panic, there's no more workers available to handle any connection, so it just times out.

```
thread 'tokio-runtime-worker' panicked at src/client.rs:59:45:
called `Result::unwrap()` on an `Err` value: ToStrError { _priv: () }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at src/client.rs:59:45:
called `Result::unwrap()` on an `Err` value: ToStrError { _priv: () }
thread 'tokio-runtime-worker' panicked at src/client.rs:59:45:
called `Result::unwrap()` on an `Err` value: ToStrError { _priv: () }
thread 'tokio-runtime-worker' panicked at src/client.rs:59:45:
called `Result::unwrap()` on an `Err` value: ToStrError { _priv: () }
thread 'tokio-runtime-worker' panicked at src/client.rs:59:45:
called `Result::unwrap()` on an `Err` value: ToStrError { _priv: () }
```

## Steps to reproduce the bug
Not sure, happened on a public instance.

**Comment by sigaloid** [comment]
Huh, seems like Reddit must send deformed [Location](https://docs.rs/http/latest/http/header/struct.ToStrError.html) headers at some point, then. I'm going to gate that unwrap call in a `let else`. This will make the error now properly display an error page to the end user, so if the underlying issue can be narrowed down, maybe we can get an end user to report a URL it happens on.

Also adding logging to the error render call, so it will show up in the output logs. (No post ID, though)
