### ISSUE TITLE
💡 Feature request: Make the UI Palette Swap Optional

### ISSUE THREAD

**Issue by np22-jpg** [redlib-org/redlib#282]
## Describe the feature you would like to be implemented

In older versions of redlib, most of the UI was white/aqua. The aqua parts are now a neon red, which users such as myself may find disorienting. This was merged in #280. It would be nice if the palette change was a setting instead, such that the old aqua UI is accessible again.

## Additional context / screenshot

Current:
![image](https://github.com/user-attachments/assets/290aa896-5d23-4e9d-8765-bd72d9402aa9)
Old:
![image](https://github.com/user-attachments/assets/f45d52de-b04d-4bb4-a139-345d8e8cb867)

**Comment by sigaloid** [comment]
Good point, this should be duplicated into an old theme file.

**Comment by DokterKaj** [comment]
Could the old theme be named "Libreddit"? Or should uses of "Reddit" be avoided everywhere?

**Comment by DokterKaj** [comment]
Also on the topic of the neon red being disorienting, what do you think of `#c2002c` for dark and `#a30026` for light/black?

**Comment by DokterKaj** [comment]
Dark:
![image](https://github.com/user-attachments/assets/2fea0fc4-3eb5-401a-a55d-5c6e26bd097b)

Light:
![image](https://github.com/user-attachments/assets/ebe84083-c478-4a32-8d22-e49898cfa244)

Logo:
![logo](https://github.com/user-attachments/assets/c01e40be-78c0-4b41-baed-19afdde6b190)

**Comment by rdadm0** [comment]
i guess we doing red ui now

**Comment by ButteredCats** [comment]
Imo the new red is far too strong on things like the sorting buttons. Also, a new favicon.ico needs to be made so the new logo appears on the tab for the site.

**Comment by Lanklow** [comment]
> Dark: ![image](https://private-user-images.githubusercontent.com/54882101/374156394-2fea0fc4-3eb5-401a-a55d-5c6e26bd097b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzA3ODEsIm5iZiI6MTcyODM3MDQ4MSwicGF0aCI6Ii81NDg4MjEwMS8zNzQxNTYzOTQtMmZlYTBmYzQtM2ViNS00MDFhLWE1NWQtNWM2ZTI2YmQwOTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA2NTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjODBjOTg4M2MxNjllNTQ2NGM2ODBiMTQ4YzkzOWM4NTMxZGM0ZDllZTYwZDkwNTJjNGEzZjZhNGFmM2ExZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2bynfdL_PZhvZxPkBkBttveWaVYzgt_98lrXQavrc-s)
> 
> Light: ![image](https://private-user-images.githubusercontent.com/54882101/374156642-ebe84083-c478-4a32-8d22-e49898cfa244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzA3ODEsIm5iZiI6MTcyODM3MDQ4MSwicGF0aCI6Ii81NDg4MjEwMS8zNzQxNTY2NDItZWJlODQwODMtYzQ3OC00YTMyLThkMjItZTQ5ODk4Y2ZhMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA2NTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MGY4MmM3MzZhNTY1ZTkwM2U0Njg2M2I5M2Y0MjNlYTQwMDkyZGYwNjAxNmExMDZmOWMxYzhiNGZmZjA1NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g230rOXMgGlLk6nLkxqfXH40tc6wSw6k0huevkSkLUY)
> 
> Logo: ![logo](https://private-user-images.githubusercontent.com/54882101/374158465-c01e40be-78c0-4b41-baed-19afdde6b190.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzA3ODEsIm5iZiI6MTcyODM3MDQ4MSwicGF0aCI6Ii81NDg4MjEwMS8zNzQxNTg0NjUtYzAxZTQwYmUtNzhjMC00YjQxLWJhZWQtMTlhZmRkZTZiMTkwLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA2NTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZWUxOTIzMjMyNzQxZWRjODZiNzEzYmFkN2RmZDhiYjE1OTQ3MjFlOTVhNGZjOGQ4MjQ2MDlkZTlkMTZiNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QnYlIxtF_dMHQLrnuiEb5mn4Oj1FLb6QopRa3Z9Ri9s)

I like the idea of setting these as the default options, then adding light/dark mode accent configuration.

**Comment by Trit34** [comment]
@Lanklow Your pics don’t show.

**Comment by DokterKaj** [comment]
@Trit34 it was a reply to my comment above: https://github.com/redlib-org/redlib/issues/282#issuecomment-2396726175

**Comment by DokterKaj** [comment]
@ButteredCats I've got a PR for that (#281) but I think I'll put it on hold until a better default red is decided on.

**Comment by DokterKaj** [comment]
> The red on black (and black on red) is completely unreadable to me, I had to change the theme. It passes WCAG 2 AA standards, but fails on AAA and APCA: https://www.myndex.com/APCA/?BG=161616&TXT=ff0000&DEV=G4g&BUF=A22 (the results is "SPOT & NON TEXT ONLY" with a minimum 84px font size.

Hm, looks like red and black simply innately don't contrast well
How does `#ff6666` look?

Dark:
![image](https://github.com/user-attachments/assets/d5cd4ed3-5ecd-42a5-a451-e7b439e1000a)

Logo:
![logo](https://github.com/user-attachments/assets/26e2f7f7-667e-480f-b1bd-3b962bfd8247)

**Comment by DokterKaj** [comment]
It's hard to tell what red would work best, since a colour that looks fine on a monitor can look too muted on a phone, while a colour that looks bright on a phone can be blinding on a monitor
I also noticed that `#ff6666` is quite similar to the NSFW tag colour (`#ff5c5d`), so I looked back at darker reds again
Personally I think `#cc3344` is a fair compromise, although it should be noted that any darker red fails abysmally at all the contrast tests

Dark:
![image](https://github.com/user-attachments/assets/19affb09-74a1-4eaa-ab3c-0b431c109a11)

Logo:
![logo](https://github.com/user-attachments/assets/8556f1a5-1616-495f-b50a-d52d582f4b84)
