### ISSUE TITLE
New style is still not complete in it's transition

### ISSUE THREAD

**Issue by SecularSteve** [redlib-org/redlib#283]
I think you've missed a spot.

That tiny icon you get in the result bar on a search page is still the LibReddit one:

![Screenshot_2024-10-11_01-37-35~3.png](https://github.com/user-attachments/assets/88686292-b40c-4e24-97ec-2fddbb912495)

**Comment by ButteredCats** [comment]
Search engines need to rescan the site in order to update that, not really sure how frequently each one rescans though. The old file has been totally replaced anyways so it wouldn't be possible for any instance running the latest git commit to serve it.

**Comment by DokterKaj** [comment]
@SecularSteve #285 should fix that
