### ISSUE TITLE
💡 Feature request: Update HLS.js to the latest version

### ISSUE THREAD

**Issue by ThePixelDeveloper** [redlib-org/redlib#29]
## Is your feature request related to a problem? Please describe.
Not a problem, but more than likely missing out on bug fixes and browser support for newer devices.

## Describe the feature you would like to be implemented
Update to the latest version of the HLS.js library

## Describe alternatives you've considered
None

## Additional context / screenshot
Currently running on v1.2.4 and the latest is [v1.5.1](https://github.com/video-dev/hls.js/releases/tag/v1.5.1). I'm also running this on my [personal instance](https://redlib-mathew-sh.fly.dev/r/SipsTea/comments/19avkha/life_as_an_american_as_seen_by_the_rest_of_the/) and it seems to be working as before.

**Comment by sigaloid** [comment]
Thanks for the report! I've updated the hls.js version.
