### ISSUE TITLE
✨ Feature parity: provide json API

### ISSUE THREAD

**Issue by RayBB** [redlib-org/redlib#300]
## How does this feature work on Reddit?

Prior to 2023 Reddit provided a nice json API for any subreddit or post.

## Describe how this could be implemented into Redlib

Since we already scrape most of the same data (if not all) and expose it via frontend and RSS it could also be exposed via json.

## Describe alternatives you've considered

I could try scraping the redlib GUI or RSS feed. However, that's really not ideal.

## Additional context / screenshot

I'm hoping to do a small analysis on a subreddit to see which tags/labels are most common on posts and which labels get the most comments. So it would be cool to be able to use a JSON api for that.

PS: Even if you decide this isn't a feature you'd support it would be nice to add a note about it to the docs.

Thanks for all your hard work on keeping this awesome project going!

**Comment by sigaloid** [comment]
I recommend you use the scraper CLI I just implemented recently in f3d2f0cc5943312f8d6c8bec50d0daf70f4116e5.

```
cargo build --release --bin scraper
./target/release/scraper  -s [sub] --count 1000 --sort hot --format json
```
This looks like it will give you all of the data you need.

**Comment by RayBB** [comment]
That worked fantastically. Thank you!

**Comment by sigaloid** [comment]
Happy to hear!
