### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1 | /r/degoogle/comments/p82v2j/searx_vs_whoogle/.json?tl=fr

### ISSUE THREAD

**Issue by jerohnimaux** [redlib-org/redlib#303]
## Describe the bug

The issue appears when using Libredirect to use redlib to open a reddit page.

## Steps to reproduce the bug

Go to :  https://reddit.com/r/degoogle/comments/p82v2j/searx_vs_whoogle/

## What's the expected behavior?

Safereddit.com should open an display the thread.

## Additional context / screenshot

On Brave 1.71.121 using Libredirect 3.0.2 

- [ ] I checked that the instance that this was reported on is running the latest git commit, or I can reproduce it locally on the latest git commit

**Comment by vytskalt** [comment]
#301

**Comment by argium** [comment]
This is still occurring

> Failed to parse page JSON data: expected value at line 1 column 1 | /r/popular/hot.json?&raw_json=1&geo_filter=GLOBAL


> ackage name | redlib
> Crate version | 0.35.1
> Git commit | bc9530821d9526d6e84d78e8bdb36dabd1f17d27
> Deploy date | 2024-11-01 6:30:44.343853514 +00:00:00
> Deploy timestamp | 1730442644
> Compile mode | Release
> SFW only | Unset
> Pushshift frontend | Unset
> RSS enabled | Unset
> Full URL | Unset

**Comment by sigaloid** [comment]
That's not the latest commit

**Comment by argium** [comment]
> That's not the latest commit

Sorry, I checked the version number with the latest release on GitHub but didn't check the git hash. My container is configured to auto update and it picked up the latest at 2am this morning and it's resolved.  Sincere thank you for keeping on top of Reddit's changes. ❤️

**Comment by sigaloid** [comment]
The reddit changes happen so quickly unfortunately it is hard to constantly release every time something breaks. At least, I'm not sure I want to commit to doing that every time. Would recommend the docker containers as those build from `main` as soon as it's pushed
