### ISSUE TITLE
🐛 Bug Report: Couldn't send request to Reddit: Rate limit - try refreshing soon | /r/oddlyspecific/hot.json?

### ISSUE THREAD

**Issue by Metrokoto** [redlib-org/redlib#312]
## Additional context / screenshot

- [ ] I checked that the instance that this was reported on is running the latest git commit, or I can reproduce it locally on the latest git commit

**Comment by sigaloid** [comment]
Instance info?

**Comment by sigaloid** [comment]
Contents of instance info page doesn't contain any private information. Visit `/info`

**Comment by sigaloid** [comment]
Update your version, you are running a 55 day old version
