### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1 | /r/discordVideos/hot.json?

### ISSUE THREAD

**Issue by barryishim** [redlib-org/redlib#320]
## Describe the bug
--> Website just doesn't work over half of the time, and says 'Failed to parse page JSON data: expected value at line 1 column 1 | /r/popular/hot.json?&raw_json=1&geo_filter=GLOBAL'

## What's the expected behavior?
 It's supposed to load posts from people that contain images, text, and videos that can be replied to.

## Additional context / screenshot

- [ yes ] I checked that the instance that this was reported on is running the latest git commit, or I can reproduce it locally on the latest git commit

**Comment by sigaloid** [comment]
Sounds like an IP ban. #318
