### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1 | /r/aww+Eyebleach+goodnews+happy+IllegallySmolCats+MadeMeSmile+oddlysatisfying+UpliftingNews+wholesomememes/hot.json?

### ISSUE THREAD

**Issue by ghost** [redlib-org/redlib#325]
## Additional context / screenshot

- [x] I checked that the instance that this was reported on is running the latest git commit, or I can reproduce it locally on the latest git commit

**Comment by sigaloid** [comment]
Are you sure you're on the latest version? :thinking: 

Try checking for a new docker image :)

**Comment by sigaloid** [comment]
_smashes keyboard_

Reopening #324. Thanks for reporting.
