### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1 | /r/hairy18/rising.json?

### ISSUE THREAD

**Issue by Daarius747** [redlib-org/redlib#330]
## Additional context / screenshot

- [ ] I checked that the instance that this was reported on is running the latest git commit, or I can reproduce it locally on the latest git commit

**Comment by Daarius747** [comment]
The page does not load up for a redlib search please fix this right now and avoid future bugs

**Comment by sigaloid** [comment]
Didn't fill out the body of the issue. update your instance please!

**Comment by Daarius747** [comment]
Hello
Everything I load redlib and wanna search reddit posts I click on the top
left redlib button sign to go home page and it never loads and crashes with
a bug and always loads into this page can you help please let me know thank

**Comment by sigaloid** [comment]
Yes, you need to try another instance. https://github.com/redlib-org/redlib-instances
