### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1 | /r/all/hot.json?

### ISSUE THREAD

**Issue by Daarius747** [redlib-org/redlib#332]
## Additional context / screenshot

- [ ] I checked that the instance that this was reported on is running the latest git commit, or I can reproduce it locally on the latest git commit

**Comment by Daarius747** [comment]
You need to fix this so it stops it is really frigging annoying the page never loads and it is on your end 👎👎👎

**Comment by JohnD-o** [comment]
They are trying their best

**Comment by sigaloid** [comment]
This is just a case of someone who doesn't really know how Redlib works. The instance operator needs to update their version. The issue is fixed in the repository
