### ISSUE TITLE
🐛 Bug Report: 6be6f89 brings back rate limit error under load

### ISSUE THREAD

**Issue by ButteredCats** [redlib-org/redlib#334]
## Describe the bug
Running 6be6f892a4eb159f5a27ce48f0ce615298071eac brings back the "Reddit rate limit exceeded" bug when Redlib is under load.

## Steps to reproduce the bug
Build Redlib on https://github.com/redlib-org/redlib/commit/6be6f892a4eb159f5a27ce48f0ce615298071eac and somehow put it under load. You'll see that the rate limit error pops up after a short time.

## What's the expected behavior?
Redlib works as normal

## Additional context / screenshot
95ab6c53856291a4d9cebb9fa5c5045031836120 works totally fine.

Running the latest commit on my desktop works fine, but as soon as I update my public facing Redlib it gets rate limited. So it only breaks with load.

Here's a log with `RUST_LOG=redlib=trace`: [redlib.log](https://github.com/user-attachments/files/17882687/redlib.log)

- [x] I checked that the instance that this was reported on is running the latest git commit, or I can reproduce it locally on the latest git commit

**Comment by LucifersCircle** [comment]
My public instance also hit the rate limit several times. Needed to wait the whole 90seconds or whatever it was for the token to refresh, then it rate limited again. I only get about 300 unique users a day.

**Comment by sigaloid** [comment]
Thanks for finding this issue! I found out the error I had made last night but I wanted to do more rigorous tests and add a proper check for this at start-up. All fixed up now. public instances should have no problems once they update
