### ISSUE TITLE
🐛 Bug Report: Rate limit check failed

### ISSUE THREAD

**Issue by ajgon** [redlib-org/redlib#335]
## Describe the bug
When running a latest (`quay.io/redlib/redlib:latest@sha256:f145df722c65dd917244edd00e20ee95ac13f12b5dd08e031610dfb16e878ca0`) version of the app, I'm getting the following error and container crashes:

```
[❌] Rate limit check failed: Rate limit check failed: expected 99, got 98
ERROR redlib >  Rate limit check failed: Rate limit check failed: expected 99, got 98
```

I noticed this error only happens if I set `REDLIB_DEFAULT_SUBSCRIPTIONS` env variable.

## Steps to reproduce the bug
```shell
docker run --rm -e REDLIB_DEFAULT_SUBSCRIPTIONS=selfhosted \
quay.io/redlib/redlib:latest@sha256:f145df722c65dd917244edd00e20ee95ac13f12b5dd08e031610dfb16e878ca0
```

## What's the expected behavior?
Container starts.

## Additional context / screenshot
None.

- [x] I checked that the instance that this was reported on is running the latest git commit, or I can reproduce it locally on the latest git commit
(note: I'm using latest container which I assume uses latest commit.)

**Comment by sigaloid** [comment]
Thanks for the report! Fixed in latest.
