### ISSUE TITLE
🐛 Bug Report: arm64 container won't start

### ISSUE THREAD

**Issue by Kirk1984** [redlib-org/redlib#34]
## Describe the bug

The container won't run on my pi4. it starts and stops. docker compose logs gives no output because it only starts for a split second.

## Steps to reproduce the bug

1. run docker compose on pi4
2. thats it

## Additional context / screenshot

It runs on my x64 nuc just fine with the same compose file (just the image was changed).

**Comment by Carbrex** [comment]
Did you uncomment the line in docker-compose.yml?

**Comment by Kirk1984** [comment]
Do you mean the image? Then yes. My compose (only change is that i merged 'security_opt' because docker compose wont start with 2 of them):

`services:
  web:
    image: quay.io/redlib/redlib:latest-arm # uncomment if you use armv7
    restart: always
    container_name: "redlib"
    environment:
      - REDLIB_DEFAULT_SHOW_NSFW=on
      - REDLIB_DEFAULT_THEME=dark
      - REDLIB_DEFAULT_FRONT_PAGE=all
      - REDLIB_DEFAULT_LAYOUT=compact
      - REDLIB_DEFAULT_WIDE=on
      - REDLIB_DEFAULT_USE_HLS=on
    ports:
      - 8080:8080
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
      - seccomp=seccomp-redlib.json
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s
`

**Comment by Kirk1984** [comment]
After a few more tests it works now. i tried running it without the compose file and it ran. so i tried a few things with the compose and the culprit is `- seccomp=seccomp-redlib.json`. Without it the container runs. That option now also prevents the container to run on x64 with the error message:

`redlib  | ensure /proc/self/fd is on procfs: operation not permitted`

I think that might have to to with the Leaky Vessels Updates surrounding docker.

**Comment by arulagrawal** [comment]
Running with the `seccomp` option results in the same error for on amd64 as well.

**Comment by sigaloid** [comment]
Weird because ARM64 is mentioned in the seccomp profile here: 

https://github.com/redlib-org/redlib/blob/c6030064f15c62a2e9e9fb5804dd9dcce44bcece/seccomp-redlib.json#L11-L16

Relevant runc spec: https://github.com/opencontainers/runc/blob/main/docs/spec-conformance.md

Could be a bug with the runtime. Can anyone try with Podman instead of Docker? Don't have any Pi's on hand.

**Comment by Kirk1984** [comment]
On my NUC (x64) it also stopped working with the seccomp profile with the mentioned error. 

Ubuntu 22.04 (both NUC and Pi) with docker-ce from dockers repo.

**Comment by sigaloid** [comment]
Interesting. I think we should probably remove the seccomp profile until we can resolve this by adding the new syscalls to the profile.

**Comment by Kirk1984** [comment]
Yes, that seems like the way to go for now. Should i close the issue?

**Comment by sigaloid** [comment]
I can do that when I push the commit commenting out the profile line. <5 min
