### ISSUE TITLE
🐛 Bug Report: error binding to [::]:8080

### ISSUE THREAD

**Issue by m4vnel** [redlib-org/redlib#341]
## Describe the bug

  First time running `redlib`. I've executed `sudo chmod +x redlib && sudo chown root:root redlib`, copied the executable to `/usr/bin` and this is the message with `RUST_BACKTRACE=full`:

```
Starting `Redlib...
Running` Redlib v0.35.1 on [::]:8080!
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.31/src/server/server.rs:81:13:
error binding to [::]:8080: error creating server listener: Address in use (os error 98)
stack backtrace:
   0:     0x79075eae9a79 - <unknown>
   1:     0x79075e7f72e3 - <unknown>
   2:     0x79075eabf642 - <unknown>
   3:     0x79075eaee802 - <unknown>
   4:     0x79075eaee66b - <unknown>
   5:     0x79075eaeed26 - <unknown>
   6:     0x79075eaee8d8 - <unknown>
   7:     0x79075eaee839 - <unknown>
   8:     0x79075eaee82c - <unknown>
   9:     0x79075e65c97f - <unknown>
  10:     0x79075e789fd7 - <unknown>
  11:     0x79075e77c2db - <unknown>
  12:     0x79075e691453 - <unknown>
  13:     0x79075e78ff57 - <unknown>
```

I've tried changing the port (although is not in use) via environment variables and `redlib` always complains about `8080`

## Additional context / screenshot
<
Linux Mint 22
Kernel 6.8.0-48-generic
I've tried the last commit, version 0.35.1
>

- [ x] I checked that the instance that this was reported on is running the latest git commit, or I can reproduce it locally on the latest git commit

**Comment by sigaloid** [comment]
Try adding "-a 0.0.0.0" - sounds like your computer may not be set up to use IPv6?

**Comment by m4vnel** [comment]
My fault. The 8080 port was in use... for another redlib instance. I tried it first with the "wget version" of the main page:

`wget https://github.com/redlib-org/redlib/releases/download/v0.31.0/redlib`

Didn't work and I tried again with the 0.35 without checking if the previous version was using the port though the service failed. 

My apologies.

**Comment by sigaloid** [comment]
No worries! Closing for now
