### ISSUE TITLE
New instance

### ISSUE THREAD

**Issue by r2fo** [redlib-org/redlib#36]
Hi,
I have setup an instance at https://redlib.r4fo.com and at http://redlib.r4focoma7gu2zdwwcjjad47ysxt634lg73sxmdbkdozanwqslho5ohyd.onion. Can you please add it to the list?

ISP: Netcup
Country: Germany
Cloudflare

**Comment by sigaloid** [comment]
It looks like you're running Libreddit, not Redlib :)

**Comment by sigaloid** [comment]
Oh :( that's a very weird thing to happen - Redlib doesn't do anything majorly different from Libreddit that would cause any proc mounts to be touched... Is this reproducible?

**Comment by sigaloid** [comment]
Update: that's a seccomp issue (https://github.com/redlib-org/redlib/issues/34) and should be fixed by removing the seccomp rule in your compose.
