### ISSUE TITLE
🐛 Bug Report: Exec format error - Architecture issue/mismatch?

### ISSUE THREAD

**Issue by MagicLike** [redlib-org/redlib#47]
## Describe the bug
I am currently trying to package Redlib for Yunohost, but whilst trying out and testing I get the following error:

```
redlib.service: Failed to execute /var/www/redlib/redlib: Exec format error
redlib.service: Failed at step EXEC spawning /var/www/redlib/redlib: Exec format error
redlib.service: Main process exited, code=exited, status=203/EXEC
redlib.service: Failed with result 'exit-code'.
```

## Steps to reproduce the bug
Running the Redlib binary via a systemd service, with the following line:
`ExecStart=__INSTALL_DIR__/redlib -a 127.0.0.1 -p __PORT__` _(The port is defined by Yunohost and gets redirected through NGINX to 80/443)_

## What's the expected behavior?
Redlib running without errors.

## Additional context / screenshot
Architecture: Arm64
OS: Debian 11

Is it possible, that the binary is not built for ARM architectures? I also tested the binary on my local system and it works flawlessly...

**Comment by sigaloid** [comment]
Are you running the release binary from GH releases? It's not built for ARM, no. You need to compile it yourself for that arch. I'm unfamiliar with Yunohost though. I'm going to close this in favor of #51 for now as we should ideally release a binary for it

**Comment by MagicLike** [comment]
> Are you running the release binary from GH releases? It's not built for ARM, no. You need to compile it yourself for that arch. I'm unfamiliar with Yunohost though. I'm going to close this in favor of #51 for now as we should ideally release a binary for it

Yes, Yunohost relies on already built binaries which it pulls and runs locally. Thanks for #51 - will wait until builds for multiple platforms are set up!
