### ISSUE TITLE
🐛 Bug Report: Failure to compile on Arch

### ISSUE THREAD

**Issue by Technetium1** [redlib-org/redlib#50]
## Describe the bug

Failure to compile `0.31.0`. Missing external functions somehow?

## Steps to reproduce the behavior

1. Attempt to build the [redlib AUR package](https://aur.archlinux.org/packages/redlib) in [clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)
2. Wait a long time
3. [Build step](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=redlib#n26) fails
5. See error

## Error

```sh
          /home/main-builder/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.17.7/pregenerated/x86_64-mont-elf.S:788:(.text+0x8b7): undefined reference to `ring_core_0_17_7_OPENSSL_ia32cap_P'
          /usr/bin/ld: /tmp/rustcgJI3q4/libring-f113115099ad4757.rlib(fef294b6a3a444d7-x86_64-mont5-elf.o):/home/main-builder/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.17.7/pregenerated/x86_64-mont5-elf.S:24: more undefined references to `ring_core_0_17_7_OPENSSL_ia32cap_P' follow
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `redlib` (bin "redlib") due to previous error
```

## Expected behavior

Successful compilation

## Additional context / screenshot
- Recently generated log of failure, will be overwritten by subsequent tests, and can be regenerated on demand: [redlib.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/redlib.log)
- Builds successfully on my own machine, but not on our build server, while both should be a clean chroot
- This issue blocks the addition of this package to Chaotic-AUR: https://github.com/chaotic-aur/packages/issues/3021
- Happy to post any more information upon request

**Comment by Kirk1984** [comment]
At first i thought that maybe i can replicate the issue on my arch machine, but then i read that it builds successfully, just not on your build server. Is there perhaps a dependency installed on your machine that the build server lacks? Perhaps something not mentioned on the AUR page?

**Comment by sigaloid** [comment]
I'm not the maintainer of that package so I cannot provide any support (nor would I know where to start as a non-AUR user). It appears to be some ssl dependency error though. I'll leave this open in case there's something I can do to help move this along in the future

**Comment by Technetium1** [comment]
The issue was related to LTO having been [enabled in our config](https://github.com/chaotic-aur/toolbox/blob/84a566c3b1cc092fce303a1543b9d65c7d8afab5/guest/etc/makepkg.conf.append#L8). The maintainer has [explicitly disabled it as a solution](https://aur.archlinux.org/cgit/aur.git/commit/?h=redlib&id=3410c2c78f85d5f54656a3985471bd21f477aced).
