### ISSUE TITLE
✨ Feature parity: RSS feeds

### ISSUE THREAD

**Issue by thunder-coding** [redlib-org/redlib#57]
## How does this feature work on Reddit?
Reddit has RSS feeds for subreddits as well as users in format:
https://reddit.com/r/reddit/.rss
https://reddit.com/user/spez/.rss

## Describe how this could be implemented into Redlib
Proxy and replace reddit with respective redlib instance URL

## Describe alternatives you've considered
I am not aware of any alternatives

## Additional context / screenshot
Irrelevant

**Comment by golfhou** [comment]
Came searching for this feature. Would be useful.  I use freshrss for reddit posts.

**Comment by maxexcloo** [comment]
Would also be nice to clean up formatting (add in full post, proxy images, maybe even add comment support)...

**Comment by nickelswitte** [comment]
I also would love this. [rss-bridge](https://github.com/RSS-Bridge/rss-bridge) also currently has [issues](https://github.com/RSS-Bridge/rss-bridge/issues/3802) with accessing reddit, so it would be lovely to use redlib instead.

**Comment by Rjvs** [comment]
@sigaloid in case it helps your thought process on mapping Reddit fields to a useable RSS feed, I thought I’d link this project that did just that (back before the rules changed) https://github.com/trashhalo/reddit-rss
