### ISSUE TITLE
🐛 Bug Report: Docker deploy fails on Render

### ISSUE THREAD

**Issue by HashLiver** [redlib-org/redlib#63]
## Describe the bug

The console show this error:
`ERROR: process "/bin/sh -c curl -L https://github.com/redlib-org/redlib/releases/latest/download/redlib-${TARGET}.tar.gz |     tar xz -C /usr/local/bin/" did not complete successfully: exit code: 1`

## Steps to reproduce the bug

* Sever: https://render.com
* Deploy type: Docker
* Deploy latest commit (https://github.com/redlib-org/redlib/commit/e79242c9e7aefa4ec5d1281385beab2faa7447ce)
* After checking, I found the problem in commit https://github.com/redlib-org/redlib/commit/3f4526debee9a4c5fc932c2c5fbe4025667d789f,  does variable `${TARGET}` working?

## Additional context / screenshot

![notitle](https://github.com/redlib-org/redlib/assets/42889797/ba81c178-4ce8-419d-8c77-6b264c4119ed)

**Comment by kevinsumner** [comment]
You must specify the TARGET build arg with the particular Rust target you want to build. These are the ones that redlib builds by default for the releases:

- x86_64-unknown-linux-musl
- aarch64-unknown-linux-musl
- armv7-unknown-linux-musleabihf
