### ISSUE TITLE
🐛 Bug Report: Couldn't send request to Reddit: error trying to connect: dns error: failed to lookup address information: Try again

### ISSUE THREAD

**Issue by AlexPewMaster** [redlib-org/redlib#78]
## Describe the bug
  Whenever I try to visit my own Redlib instance at [redlib.reallyaweso.me](https://redlib.reallyaweso.me), I get this error:

```
Couldn't send request to Reddit: error trying to connect: dns error: failed to lookup address information: Try again
```

## Steps to reproduce the bug
1. Go to [redlib.reallyaweso.me](https://redlib.reallyaweso.me)
2. See error

## What's the expected behavior?
I should normally see the frontpage of my own instance.

## Additional context / screenshot
The logs of the Docker container seem to be reporting the same issue:
```
redlib  |  ERROR redlib::utils > Error page rendered: Couldn't send request to Reddit: error trying to connect: dns error: failed to lookup address information: Try again
```

**Comment by HakaishinShwet** [comment]
@AlexPewMaster did you find any solution for this one?

**Comment by 0x09AF** [comment]
I started getting this message on the main page of my own instance. But seems like yours has been fixed. What was the solution?

**Comment by rhee876527** [comment]
Suddenly caught this bug as well. Seems it has something to do with adding more than 1 subreddit to the cookies.

**Comment by patrick330602** [comment]
Had the similar problem; it seems that if I do not subscribe anything, the error won’t appear; but searching will return no posts for me

**Comment by alscaldas** [comment]
I installed Redlib yesterday and it  was working perfectly until a couple of minutes ago. Same issue as already related. I also noticed that If for example I open a new icognito tab it works fine (but with a clean profile and none of my previous subscriptions).

**Comment by iSack97** [comment]
Got the same problem on my own instance, reddit must have changed things....

**Comment by sigaloid** [comment]
Fixed in https://github.com/redlib-org/redlib/commit/273d889f1b05b23ca1a038fd36da564289b6455a

Release needs some kinks worked out, clone from source if you need this fix asap
