### ISSUE TITLE
🐛 Bug Report: NSFW subs will sometimes return no posts

### ISSUE THREAD

**Issue by accountForIssues** [redlib-org/redlib#8]
Thank you so much for forking libreddit and keeping it maintained and up to date with all the shenanigans Reddit is doing.

## Describe the bug
Sometimes, visiting an nsfw sub will return "No posts were found.".
I haven't been able to properly reproduce it as it'll work fine after sometime. And sometimes it works on one device and doesn't on another (at the same time).

This also happened with libreddit (with the oauth PR merged).

I wonder if this is a "test" by Reddit to disable nsfw subs via their public API and only allow to logged in users.

## Steps to reproduce the bug
Visit any NSFW subreddit.

## What's the expected behavior?
All posts are visible.

## Additional context / screenshot
Deployed on fly.dev -- everything else works fine -- No IP blocked errors since ~2 weeks.

**Comment by sigaloid** [comment]
Thanks for the report. I'm able to reproduce this on r/drugs. It's a result of the sub being gated/quarantined. Reddit does this to some subs - it's another example of restrictions similar to NSFW tagging. This is a breaking change from Libreddit prior to OAuth spoofing. We handled it okay before then. Probably the case of another cookie being added.

What's really curious is it working on one device but not another simultaneously. There's a cache on the Reddit requests so it should **work** or **not work**, on all **devices** from the same **instance** at the same **time**.

**Comment by sigaloid** [comment]
Oh, that's so interesting... Reddit refuses to serve gated content to **any** iOS users. My spoofing randomly chooses either an iOS or a Reddit user client to spoof... Let me see if there's some kind of parameter I can add to the call, showing I've opted into the gated content. Maybe by default iOS doesn't allow it, but if I add the parameter, it will work. I'd prefer this to solely spoofing Android as my workflow primarily uses iOS to reverse engineer behavior.

**Comment by accountForIssues** [comment]
Is this related ? The app could be sending another cookie depending on the app settings. https://old.reddit.com/r/help/comments/1890jrn/cannot_allow_nsfw_content_iphone/

**Comment by sigaloid** [comment]
NSFW content works as expected, it's just gated content that is broken. Though there might be a similar thing for gated. I'm going to do more investigating; reddit DOES serve gated content to logged in users if you're subscribed to the sub. Which we can't do on anonymous. But maybe it's as simple as adding the same header/cookie

**Comment by accountForIssues** [comment]
Hmm, I cannot seem to be able to access any nsfw sub. I tried r/drugs which shows the "gated" prompt. Clicking on continue leads to an empty sub. For nsfw subs, it just leads to an empty sub.

Probably any sub from here will work (obvious nsfw warning) -  https://old.reddit.com/r/ListOfSubreddits/wiki/nsfw

**Comment by sigaloid** [comment]
Hmm. My testing probably got lucky with Android every time. iOS does have rules about NSFW content being accessible. Let's see if there's anything we can do to make it visible with the regular JSON api as an iOS client.

**Comment by sigaloid** [comment]
Okay, I don't believe there's a way around this particular issue (read on). The reason is, we're identifying as an iOS device voluntarily. I cannot find a way for an iOS device to fetch this without using the GQL API, which is not done yet for a number of reasons. The iOS app doesn't use the oauth.reddit.com json endpoints at all it seems. Android does though.

For now, I'm going to simply only spoof Android clients. This gives us gated and NSFW access all in one.
