### ISSUE TITLE
🐛 Bug Report: Wrong container registry reference

### ISSUE THREAD

**Issue by 7677865466** [redlib-org/redlib#9]
## Describe the bug
Readme instructions need to be updated. The container tags referring to both arm and armv7 are outdated.

## Steps to reproduce the bug
"podman pull quay.io/redlib/redlib:arm" results in an error as the "arm" tag does not exist. This needs to be replaced by "quay.io/redlib/redlib:latest-arm" in the documentation.

Thanks for your efforts in updating Libreddit and creating this new repository!

**Comment by sigaloid** [comment]
Thanks for the report, fixed!
